# server
server:
  port: 8080

# mysql
datasource:
  username: 
  password: 
  host: 
  port: 
  database: 
  charset: 
  parseTime: 
  loc: 

# email
email:
  alias: 
  host: 
  port: 
  username: 
  password: 
