# server
server:
  port: 8080

# mysql
datasource:
  username: root
  password: john156
  host: 127.0.0.1
  port: 3306
  database: library
  charset: utf8mb4
  parseTime: true
  loc: Asia/Shanghai

# email
email:
  alias: HuangJ
  host: smtp.163.com
  port: 465
  username: huangj156@163.com
  password: EFVJZERSRMXIQHPI